---
title: "ReAnalysis Table"
author: "CT"
date: "Thursday, December  05, 2016"
output:
  word_document: default
  html_document: default
note: Re analysis data compilation; Days, TT and Photop.
---

Aim:

- Reads raw data
- Clean data (remove NAs)
- Check the data
- Calculate days to flowering
- Saves technically consistent data

```{r, warning=FALSE}

library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)
library(scales)
library(here)
```

Paths

```{r   loadFile}
print(paste0("Here is: ", here()))
chapterPath <- paste0(here(),"/Chapter_03") 
rawPath <- paste0(chapterPath,"/Data/RawData/")
workDPath <- paste0(chapterPath,"/Data/WorkedData/")

```

Here loading the database: publication, location and dates of experiments 

```{r}
#create file
df_Data <- read.table(paste0(rawPath,"RawDatabase.txt"),header=TRUE)

#head(df_Data)

summary(df_Data)

summary(df_Data$AuthorYear)
```

```{r}
#change formats 

df_Data$SowingDate <-dmy(df_Data$SowingDate)
df_Data$StartFlowering <-dmy(df_Data$StartFlowering)

str(df_Data)
```

```{r}
#Calculate DaysToFlower

df_Data <- df_Data %>%
na.omit() %>%
mutate(DaysToFlower=(StartFlowering-SowingDate))
```

Check data quality , graph

```{r, fig.width=12}
df_Data %>%
  ggplot(aes(x=Location,y=DaysToFlower))+
  geom_jitter(width = 0.2)+
  geom_boxplot(alpha=0.2)+
theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  
  facet_wrap(~Country)
```


```{r, , fig.width=12}

  df_Data%>%
  ggplot(aes(x=month(SowingDate),y=DaysToFlower,colour=Location, shape=Country))+
  geom_jitter(width = 0.2)+
  geom_point(alpha=0.2)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  
  facet_wrap(~Country)
```


```{r, fig.height=5, fig.width=10,warning=FALSE}

df_Data%>% 
  ggplot(aes(x=month(SowingDate), y=DaysToFlower))+
  geom_boxplot()+
  geom_jitter(width = 0.1, aes(colour=Location))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  #theme(legend.position="none")+
  labs(x=" Month", y="Days to flower")+
  facet_wrap(~Country)


```


Graph Box Plot 

```{r GraphBoxPlot, warning=FALSE, fig.width=12}

# Graph DAS and Location 

df_Data %>%
  filter(Location != "Canberra"& Location != "Lismore") %>%
  ggplot(aes(x=Country, y=DaysToFlower)) + 
  geom_boxplot(alpha =0.2) +
  geom_violin(alpha =0.2)+
  geom_jitter(aes(colour=Location), width=0.25)+
  labs(y="DAS to flower ",x="Country")
  

```


```{r,  fig.width=12}
# Graph DAS and Location by month 

df_Data %>%
  filter(Location != "Canberra"& Location != "Lismore"& Location != "Perth") %>%
  ggplot(aes(x=month(SowingDate), y=DaysToFlower))+
  geom_boxplot(alpha=0.2)+
  geom_jitter(width = 0.1, aes(colour=Location))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  
  #theme(legend.position="none")+
  xlab("Month")+ ylab (expression(paste("PM(",mu, "g/", m^3,")", sep=""))) +
     scale_x_discrete(labels=month.abb) +
  facet_wrap(~Country)
```



```{r}
write.table(df_Data,file=paste0(workDPath,"df_DaysToFlower.txt"), row.names = FALSE, quote = FALSE, sep="\t")
```

